name: æ„å»ºvless-configToGithub

on:
  workflow_dispatch:
    inputs:
      docker_name:
        description: "Docker é•œåƒåç§°"
        required: true
        type: string
      build_version:
        description: "é•œåƒç‰ˆæœ¬"
        required: true
        type: string
        default: "0.0.1"
      github_WORKDIR:
        description: "githubå·¥ä½œç›®å½•"
        required: true
        type: string
        default: "vless-config"

jobs:
  build:
    runs-on: ubuntu-latest

    # ğŸ‘‡ æ·»åŠ æƒé™å£°æ˜
    permissions:
      contents: read
      packages: write  # å…è®¸æ¨é€åŒ…åˆ° ghcr.io

    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@v4

      - name: è®¾ç½®QEMU
        uses: docker/setup-qemu-action@v3

      - name: è®¾ç½®Buildx
        uses: docker/setup-buildx-action@v3

      - name: ç™»å½•Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: æ„å»ºå¹¶æ¨é€Dockeré•œåƒ
        uses: docker/build-push-action@v5
        with:
          context: ./${{ github.event.inputs.github_WORKDIR }}
          file: ./${{ github.event.inputs.github_WORKDIR }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.docker_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.docker_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.docker_name }}:${{ github.event.inputs.build_version }}
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
